# Test that dividing by 0 yields an exceptional state which is
# recovered by the catch statement.
# Should print '3'
x := 2
try (
  x := 5 / 0
  while true skip
)
catch x := x + 1
print x
